# Generated by Django 5.1.6 on 2025-03-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_question', models.TextField()),
                ('user_id', models.IntegerField()),
                ('date_time', models.DateTimeField()),
                ('ai_answer', models.TextField()),
            ],
        ),
    ]
